export const getMenuData = [
  {
    category: true,
    title: 'Dashboard',
  },
  {
    title: 'Dashboard',
    key: 'dashboard',
    url: '/dashboard',
    icon: 'fe fe-layout',
    roles: ['superadmin', 'admin', 'editor'],
  },
  {
    category: true,
    title: 'Content',
  },
  {
    title: 'Editors\' Picks',
    key: 'postpicks',
    url: '/content/picks',
    icon: 'fe fe-edit',
    roles: ['admin', 'editor'],
  },
  {
    category: true,
    title: 'Members',
  },
  {
    title: 'Members',
    key: 'members',
    count: 0,
    url: '/members',
    icon: 'fe fe-user',
    roles: ['superadmin', 'admin', 'editor'],
  },
  {
    category: true,
    title: 'Contribution',
  },
  {
    title: 'Contributions',
    key: 'contributions',
    count: 0,
    url: '/contributions',
    icon: 'fe fe-dollar-sign',
    roles: ['superadmin', 'admin', 'editor'],
  },
  {
    title: 'Reminders',
    key: 'reminders',
    count: 0,
    url: '/contributions/reminders',
    icon: 'fe fe-dollar-sign',
    roles: ['superadmin', 'admin', 'editor'],
  },
  {
    category: true,
    title: 'Architectures',
  },
  {
    title: 'Cache System',
    key: 'cache-system',
    url: '/system/cache',
    icon: 'fe fe-hard-drive',
    roles: ['superadmin', 'admin', 'editor'],
  },
  {
    category: true,
    title: 'System',
  },
  {
    title: 'Users',
    key: 'system-users',
    count: 0,
    url: '/system/users',
    icon: 'fe fe-users',
    roles: ['superadmin', 'admin', 'editor'],
  },
  {
    title: 'Danger Zone',
    key: 'danger-zone',
    icon: 'fe fe-alert-triangle',
    disabled: true,
  },
]
